### ISSUE TITLE
Before 1v there were option to exclude_none in yaml() method. Is there such a thing now? I dont see it in to_yaml_str

### ISSUE THREAD

**Issue by dinjazelena** [NowanIlfideme/pydantic-yaml#111]

**Comment by NowanIlfideme** [comment]
Hi, in the future please use the description for long text, and keep the title short. But thanks for bringing this up, I'll check it out. I think that you can pass it via kwargs (can't check since not at PC) but it would be good to pass through to Pydantic if it's not the case. And if it already works I should update the docs.

**Comment by dinjazelena** [comment]
Works as just putting it as keyword arg.
Thanks
